### ISSUE TITLE
Add ability to specify /etc/hosts entries

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgcloud#119]
We need a spark-master entry on Toil workers that connect to an external Spark/HDFS cluster.

**Comment by fnothaft** [comment]
Still no dice:

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/opt/sparkbox/tools/local/lib/python2.7/site-packages/cgcloud/spark_tools/__init__.py", line 92, in start
    self.__setup_etc_hosts( )
  File "/opt/sparkbox/tools/local/lib/python2.7/site-packages/cgcloud/spark_tools/__init__.py", line 442, in __setup_etc_hosts
    (entry.split( ':', 1 ) for entry in etc_hosts_entries.split( ',' )) }
  File "/opt/sparkbox/tools/local/lib/python2.7/site-packages/cgcloud/spark_tools/__init__.py", line 441, in <dictcomp>
    etc_hosts_entries = { ip.strip(): host.strip() for ip, host in
ValueError: need more than 1 value to unpack
```

I'm going to shut my cluster off for now; I'll pick back up in the AM. I can sort this out and will PR my changes at you.

**Comment by hannes-ucsc** [comment]
The image needs to be recreated. The changes were to {spark,mesos}-tools which are baked into the image.

**Comment by fnothaft** [comment]
I did rebuild cgcloud and recreate the image before running. I'll look at this again this morning with a fresh cluster.
