### ISSUE TITLE
Spark slaves fail to register with master

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgcloud#122]
/var/log/upstart/sparkbox.log on a slave: 

```
NFO:cgcloud.spark_tools:Registering with master
Host key verification failed.^M
WARNING:cgcloud.spark_tools:rsync returned 255, retrying in 5s
Host key verification failed.^M
WARNING:cgcloud.spark_tools:rsync returned 255, retrying in 5s
Host key verification failed.^M
WARNING:cgcloud.spark_tools:rsync returned 255, retrying in 5s
Host key verification failed.^M
WARNING:cgcloud.spark_tools:rsync returned 255, retrying in 5s
Host key verification failed.^M
WARNING:cgcloud.spark_tools:rsync returned 255, retrying in 5s
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/opt/sparkbox/tools/local/lib/python2.7/site-packages/cgcloud/spark_tools/__init__.py", line 105, in start
    self.__register_with_master( )
  File "/opt/sparkbox/tools/local/lib/python2.7/site-packages/cgcloud/spark_tools/__init__.py", line 393, in __register_with_master
    raise RuntimeError( "Failed to register with master" )
RuntimeError: Failed to register with master
```

**Comment by hannes-ucsc** [comment]
Caused by silly typo in SparkTools.
