### ISSUE TITLE
Unable to run cwltoil on toil-latest-box

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/cgcloud#143]
Following the instructions to create a minimal toil cluster, the image does not have a working cwltoil:

```
$ cgcloud create -IT -z us-west-2a toil-latest-box
...
$ cgcloud create-cluster toil -z us-west-2a -s 1 -t t2.micro
...
$ cgcloud ssh -z us-west-2a toil-leader
mesosbox@ip-172-31-27-16:~$ cwltoil
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev133', 'console_scripts', 'cwltoil')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2201, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2218, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'cwltool==1.0.20160408133555' distribution was not found and is required by the application
mesosbox@ip-172-31-27-16:~$ 
```

**Comment by tetron** [comment]
I built a new image using toil-latest-box this morning, toil is newer but cwltoil is still broken:

```
mesosbox@ip-172-31-31-240:~$ cwltoil
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev134', 'console_scripts', 'cwltoil')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2228, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2245, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'cwltool==1.0.20160411194133' distribution was not found and is required by the application
mesosbox@ip-172-31-31-240:~$ logout
```

**Comment by hannes-ucsc** [comment]
Works for me:

```
(bd2k:/__me__/)hannes-mbpr:cgcloud hannes $ cgcloud create toil-latest-box
INFO: Using zone 'us-west-2a' and namespace '/hannes/'
INFO: Looking up default image for role toil-latest-box and virtualization type hvm, ... 
--- 8< --- snip --- 8< ---
[52.32.248.246] sudo: service mesosbox start
[52.32.248.246] out: mesosbox start/running
[52.32.248.246] out: 

INFO: Run 'cgcloud ssh toil-latest-box' to start using this box.
(bd2k:/__me__/)hannes-mbpr:cgcloud hannes $ cgcloud ssh toil-latest-box
INFO: Using zone 'us-west-2a' and namespace '/hannes/'
INFO: Binding to instance ... 
INFO: ... waiting for instance i-83b4ec5b ... 
INFO: ... running, waiting for assignment of public IP ... 
INFO: ... assigned, waiting for SSH port ... 
INFO: ... open ... 
INFO: ... instance ready.
The authenticity of host 'ec2-52-32-248-246.us-west-2.compute.amazonaws.com (52.32.248.246)' can't be established.
ECDSA key fingerprint is SHA256:Zli/ASNGX9brFSOVayFSQ+s2iFrkwzx90uxSb86s//U.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'ec2-52-32-248-246.us-west-2.compute.amazonaws.com,52.32.248.246' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

 System information disabled due to load higher than 1.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud


*** System restart required ***
Last login: Tue Apr 12 23:56:43 2016 from c-67-180-92-62.hsd1.ca.comcast.net
mesosbox@ip-172-31-18-228:~$ cwltoil 
usage: cwltoil [-h] [--logOff] [--logCritical] [--logError] [--logWarning]
               [--logInfo] [--logDebug] [--logLevel LOGLEVEL]
               [--logFile LOGFILE] [--rotatingLogging] [--workDir WORKDIR]
               [--stats] [--clean {always,onError,never,onSuccess}]
               [--cleanWorkDir {always,never,onSuccess,onError}] [--restart]
               [--batchSystem BATCHSYSTEM] [--scale SCALE]
               [--mesosMaster MESOSMASTERADDRESS]
               [--parasolCommand PARASOLCOMMAND]
               [--parasolMaxBatches PARASOLMAXBATCHES] [--defaultMemory INT]
               [--defaultCores FLOAT] [--defaultDisk INT] [--defaultCache INT]
               [--maxCores INT] [--maxMemory INT] [--maxDisk INT]
               [--retryCount RETRYCOUNT] [--maxJobDuration MAXJOBDURATION]
               [--rescueJobsFrequency RESCUEJOBSFREQUENCY]
               [--maxLogFileSize MAXLOGFILESIZE] [--realTimeLogging]
               [--sseKey SSEKEY] [--cseKey CSEKEY]
               [--setEnv NAME=VALUE or NAME]
               [--servicePollingInterval SERVICEPOLLINGINTERVAL]
               [--badWorker BADWORKER]
               [--badWorkerFailInterval BADWORKERFAILINTERVAL]
               [--jobStore JOBSTORE] [--conformance-test] [--no-container]
               [--quiet] [--basedir BASEDIR] [--outdir OUTDIR] [--version]
               jobStore cwltool cwljob
cwltoil: error: too few arguments
mesosbox@ip-172-31-18-228:~$ pip list
apt-xapian-index (0.45)
avro (1.8.0)
bd2k-python-lib (1.13.dev14)
boto (2.38.0)
cffi (1.5.2)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
cwltool (1.0.20160411194133)
google-common (0.0.1)
html5lib (0.999)
isodate (0.5.4)
jsonpatch (1.3)
jsonpointer (1.0)
keepalive (0.5)
Landscape-Client (14.12)
mesos (0.25.0)
mesos.interface (0.25.0)
mistune (0.7.2)
oauth (1.0.1)
PAM (0.4.2)
pip (8.1.1)
prettytable (0.7.2)
protobuf (2.6.1)
psutil (3.0.1)
pycparser (2.14)
pycurl (7.19.3)
PyNaCl (0.3.0)
pyOpenSSL (0.13)
pyparsing (2.1.1)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
rdflib (4.2.1)
rdflib-jsonld (0.3)
requests (2.2.1)
schema-salad (1.7.20160316203940)
setuptools (20.7.0)
shellescape (3.4.1)
six (1.5.2)
SPARQLWrapper (1.7.6)
ssh-import-id (3.21)
toil (3.2.0a2.dev134)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
typing (3.5.0.1)
urllib3 (1.7.1)
virtualenv (15.0.1)
zope.interface (4.0.5)
mesosbox@ip-172-31-18-228:~$ exit
logout
Connection to ec2-52-32-248-246.us-west-2.compute.amazonaws.com closed.
```

How did you install cgcloud in the first place and how did you upgrade it after I merged the fix?

**Comment by hannes-ucsc** [comment]
IOW, you should have 1.4a1.dev266 installed via pip or the latest master if you installed from a checkout via `make develop`.

**Comment by tetron** [comment]
Sorry about that, I was confused about how cgcloud works and didn't update my cgcloud git repo.  Trying that now.

**Comment by hannes-ucsc** [comment]
No, worries. Don't forget to run `make develop && make sdist` (yes, invoke make twice) after updating the repo.

**Comment by tetron** [comment]
Yes, I rebuilt images and it worked.  Thanks.
