### ISSUE TITLE
Throw explicit error if current user can't be determined

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgcloud#20]
_From @hannes-ucsc on March 31, 2015 16:25_

User didn't have permissions to call iam.get_user() which returned None and then failed down the stream with

```
Using zone 'us-west-1b' and namespace '/_me__/'
Traceback (most recent call last):
  File "/usr/local/bin/cgcloud", line 9, in <module>
    load_entry_point('cgcloud-core==1.0.dev1', 'console_scripts', 'cgcloud')()
  File "/Library/Python/2.7/site-packages/cgcloud/core/ui.py", line 28, in main
    try_main( args )
  File "/Library/Python/2.7/site-packages/cgcloud/core/ui.py", line 23, in try_main
    app.run( args )
  File "/Library/Python/2.7/site-packages/cgcloud/lib/util.py", line 212, in run
    command.run( options )
  File "/Library/Python/2.7/site-packages/cgcloud/core/commands.py", line 65, in run
    ctx = Context( availability_zone=zone, namespace=namespace )
  File "/Library/Python/2.7/site-packages/cgcloud/lib/context.py", line 139, in __init_
    namespace = self.resolve_me( namespace )
  File "/Library/Python/2.7/site-packages/cgcloud/lib/context.py", line 534, in resolve_me
    me = self.drop_hostname( me )
  File "/Library/Python/2.7/site-packages/cgcloud/lib/context.py", line 523, in drop_hostname
    n = email.index( "@" )
AttributeError: 'NoneType' object has no attribute 'index'
```

_Copied from original issue: BD2KGenomics/cgcloud-core#9_

**Comment by hannes-ucsc** [comment]
Dupe of #61
