### ISSUE TITLE
cgcloud register-key error

### ISSUE THREAD

**Issue by jpdna** [BD2KGenomics/cgcloud#234]
I'm setting up my aws credentials on a new computer and installing a fresh copy of cgcloud following:
https://github.com/BD2KGenomics/cgcloud/blob/master/core/README.rst

and I just can't seem to get cgcloud register-key to accept my credentials.
I am getting

```
cgcloud register-key ~/.ssh/id_rsa.pub
WARNING: IAMConnection.get_user() failed.
Traceback (most recent call last):
  File "/home/paschallj/adam_dep/test3/cgcloud/local/lib/python2.7/site-packages/cgcloud/lib/context.py", line 596, in iam_user_name
    return self.iam.get_user( ).user_name
  File "/home/paschallj/adam_dep/test3/cgcloud/local/lib/python2.7/site-packages/boto/jsonresponse.py", line 86, in __getattr__
    raise AttributeError
AttributeError
ERROR: An error occurred. Using zone 'us-east-1a' and namespace '/__me__/'
ERROR: Can't determine current IAM user name. Be sure to put valid AWS credentials in ~/.boto or ~/.aws/credentials. For details, refer to http://boto.readthedocs.org/en/latest/boto_config_tut.html. On an EC2 instance that is authorized via IAM roles, you can set the CGCLOUD_ME environment variable (uncommon).
```

I've tried setting env variables, .boto and .aws/credentials

Of note, with the same credentials I'm getting correct seeming response from running in the same virtualenv
the python repl, with either the env variable or .boto set or .aws/credentials set
So - I think the credentials themselves work.

```
>>> from boto.iam.connection import IAMConnection
>>> jp = IAMConnection()
>>> jp.get_user()
```

and

```
 aws iam get-user
```

gives back a "USER {... } " json object that looks like it is happy.
But, I try next in the same shell session `cgcloud register-key ~/.ssh/id_rsa.pub`
and get the error above.

What am I missing?

**Comment by jpdna** [comment]
hmmm, OK I resolved this creating a new IAM key after all.
