### ISSUE TITLE
Upper case letters in namespace break assertion in security group setup

### ISSUE THREAD

**Issue by jpdna** [BD2KGenomics/cgcloud#245]
I've followed the README  instructions on installation of cgcloud and cgcloud-spark
and I am getting the error below when I get to the point of starting a cgcloud spark-box.

Note,  `cgcloud create generic-ubuntu-trusty-box` works fine.

```
(cgcloud) paschallj@jp1:~/v1_cgcloud$ cgcloud create -IT spark-box
INFO: Using zone 'us-west-2a' and namespace '/Justin/'
INFO: Looking up default image for role spark-box and virtualization type hvm, ... 
INFO: ... found ami-fe8c2f9e.
INFO: Setting up security group ...
Traceback (most recent call last):
  File "/home/paschallj/v1_cgcloud/cgcloud/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/lib/util.py", line 308, in run
    command.run( options )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 85, in run
    return self.run_in_ctx( options, ctx )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 109, in run_in_ctx
    return self.run_on_role( options, ctx, role )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 128, in run_on_role
    return self.run_on_box( options, box )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 567, in run_on_box
    spec = box.prepare( **self.preparation_kwargs( options, box ) )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/box.py", line 477, in prepare
    security_group_ids = self.__setup_security_groups( vpc_id=vpc_id )
  File "/home/paschallj/v1_cgcloud/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/box.py", line 316, in __setup_security_groups
    assert len( sgs ) == 1
AssertionError

```

Not sure what to do next to diagnose.

I did set this up on a new machine with a new local ssh key and so had to re-register with `cgcloud register-key` and use `--force`
However, given the cgcloud-core login works I assume the aws credential and key registration went fine.

**Comment by hannes-ucsc** [comment]
This doesn't seem to be 1.6.0a1 which I assume you intend to use. What does `/home/paschallj/v1_cgcloud/cgcloud/bin/pip list` print?

**Comment by jpdna** [comment]
```
(cgcloud) paschallj@jp1:~/v1_cgcloud$ /home/paschallj/v1_cgcloud/cgcloud/bin/pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bd2k-python-lib (1.14a1.dev35)
boto (2.38.0)
cgcloud-core (1.5.6)
cgcloud-lib (1.5.6)
cgcloud-spark (1.5.6)
ecdsa (0.13)
Fabric (1.10.3)
futures (3.0.4)
paramiko (1.16.0)
pip (9.0.1)
pkg-resources (0.0.0)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (28.8.0)
subprocess32 (3.2.7)
tabulate (0.7.5)
wheel (0.30.0a0)

```

OK - so I'll clone the github repo so I get current master and try again.   But do you think the version is related to this security group problem?

**Comment by jpdna** [comment]
It may unrelated to above, but I just cloned repo from cgcloud master, and ran
`make develop sdist`
and then directly after that ran
`cgcloud create generic-ubuntu-trusty-box`
to test just cgcloud-core before trying cgcloud spark.

However I get this error:

```
...
[35.164.25.238] out: ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /packages/c1/f5/0fa2938278416117d203551990dd57e101289899e2fd64a657078ef76b46/bd2k-python-lib-1.14a1.dev35.tar.gz (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
[35.164.25.238] out: 
[35.164.25.238] out: Storing debug log for failure in /home/ubuntu/.pip/pip.log
[35.164.25.238] out: 


Fatal error: run() received nonzero return code 2 while executing!

Requested: /opt/cgcloudagent/bin/pip install --allow-external argparse /home/ubuntu/cgcloud-lib-1.6.0a1.dev0.tar.gz /home/ubuntu/cgcloud-agent-1.6.0a1.dev0.tar.gz
Executed: /bin/bash -l -c "/opt/cgcloudagent/bin/pip install --allow-external argparse /home/ubuntu/cgcloud-lib-1.6.0a1.dev0.tar.gz /home/ubuntu/cgcloud-agent-1.6.0a1.dev0.tar.gz"

Aborting.
INFO: Terminating instance ...

```

pip list there is:

```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bd2k-python-lib (1.14a1.dev35)
boto (2.38.0)
cgcloud-core (1.6.0a1.dev0, /home/paschallj/v2_cgcloud/cgcloud/core/src)
cgcloud-jenkins (1.6.0a1.dev0, /home/paschallj/v2_cgcloud/cgcloud/jenkins/src)
cgcloud-lib (1.6.0a1.dev0, /home/paschallj/v2_cgcloud/cgcloud/lib/src)
cgcloud-mesos (1.6.0a1.dev0, /home/paschallj/v2_cgcloud/cgcloud/mesos/src)
cgcloud-spark (1.6.0a1.dev0, /home/paschallj/v2_cgcloud/cgcloud/spark/src)
cgcloud-toil (1.6.0a1.dev0, /home/paschallj/v2_cgcloud/cgcloud/toil/src)
ecdsa (0.13)
Fabric (1.10.3)
futures (3.0.4)
paramiko (1.16.0)
pip (9.0.1)
pkg-resources (0.0.0)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (28.8.0)
subprocess32 (3.2.7)
tabulate (0.7.5)
wheel (0.30.0a0)

```

**Comment by hannes-ucsc** [comment]
That `Connection reset by peer` error is a PyPI outage. I would try it again. You are already past the point where the previous attempt failed with that assertion error in your OP.

**Comment by jpdna** [comment]
Above I was trying to run 
`cgcloud create generic-ubuntu-trusty-box` from the 1.6.0a1 code.
You are correct, on retry it worked.

However, I am still getting a, now slightly different, error for spark when running:

```
(cgcloud2) paschallj@jp1:~/v2_cgcloud/cgcloud/spark$ cgcloud create -IT spark-box
INFO: Using zone 'us-west-2a' and namespace '/Justin/'
INFO: Looking up default image for role spark-box and virtualization type hvm, ... 
INFO: ... found ami-fe8c2f9e.
INFO: Setting up security group ...
Traceback (most recent call last):
  File "/home/paschallj/v2_cgcloud/cgcloud2/bin/cgcloud", line 11, in <module>
    load_entry_point('cgcloud-core==1.6.0a1.dev0', 'console_scripts', 'cgcloud')()
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/home/paschallj/v2_cgcloud/cgcloud/lib/src/cgcloud/lib/util.py", line 308, in run
    command.run( options )
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/commands.py", line 85, in run
    return self.run_in_ctx( options, ctx )
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/commands.py", line 109, in run_in_ctx
    return self.run_on_role( options, ctx, role )
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/commands.py", line 128, in run_on_role
    return self.run_on_box( options, box )
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/commands.py", line 567, in run_on_box
    spec = box.prepare( **self.preparation_kwargs( options, box ) )
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/box.py", line 479, in prepare
    security_group_ids = self.__setup_security_groups( vpc_id=vpc_id )
  File "/home/paschallj/v2_cgcloud/cgcloud/core/src/cgcloud/core/box.py", line 319, in __setup_security_groups
    sg = sgs[ 0 ]
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/paschallj/v2_cgcloud/cgcloud2/lib/python2.7/site-packages/bd2k_python_lib-1.14a1.dev35-py2.7.egg/bd2k/util/retry.py", line 95, in repeated_attempt
  File "/home/paschallj/v2_cgcloud/cgcloud/lib/src/cgcloud/lib/ec2.py", line 394, in inconsistencies_detected
    if e.code == 'InvalidGroup.NotFound': return True
AttributeError: 'exceptions.AssertionError' object has no attribute 'code'
```

Is there something I should be doing before hand myself to configure security groups?

**Comment by hannes-ucsc** [comment]
Can you try with an all-lower-case namespace? Just being paranoid here.

**Comment by hannes-ucsc** [comment]
I can reproduce this with an upper-case letter in the namespace. All lower-case works.

**Comment by jpdna** [comment]
Thanks Hannes!
Works for me now too with all-lower-case namespace.
