### ISSUE TITLE
Spark can't find Hadoop

### ISSUE THREAD

**Issue by beaunorgeot** [BD2KGenomics/cgcloud#32]
Spark loads the default Hadoop parameters instead of taking them from the Hadoop config files.
This results in failed spark/adam jobs
Setting HADOOP_HOME doesn't solve this problem
But setting spark/ADAM_OPTS does
ADAM_OPTS="--driver-class-path /opt/sparkbox/hadoop/etc/hadoop"
Below are traces for the ADAM call that pointed out the bug, our replication of the error using the spark shell, and some troubleshooting to rule out other potential causes 

SPARK can’t find Hadoop

/usr/bin/time /home/sparkbox/adam-distribution_2.10-0.17.0/bin/adam-submit transform hdfs://spark-master:8020/C835.HCC1143_BL._.bam hdfs://spark-master:8020/C835.HCC1143_BL.4.adam
Spark assembly has been built with Hive, including Datanucleus jars on classpath
2015-06-03 22:54:13 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: hdfs://spark-master:8020/C835.HCC1143_BL._.bam, expected: file:///
    at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:643)
    at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:79)
    at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:506)
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:724)
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:501)
    at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:397)
    at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1411)
    at org.bdgenomics.adam.rdd.ADAMContext.loadBam(ADAMContext.scala:237)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadAlignments$1.apply(ADAMContext.scala:516)
    at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadAlignments$1.apply(ADAMContext.scala:513)
    at org.apache.spark.rdd.Timer.time(Timer.scala:57)
    at org.bdgenomics.adam.rdd.ADAMContext.loadAlignments(ADAMContext.scala:511)
    at org.bdgenomics.adam.cli.Transform.run(Transform.scala:148)
    at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:53)
    at org.bdgenomics.adam.cli.Transform.run(Transform.scala:85)
    at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:105)
    at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---

We can replicate the problem in the spark shell

scala> fs.isDirectory(new Path(new URI("hdfs://spark-master:8020/C835.HCC1143_BL.4.bam")))
java.lang.IllegalArgumentException: Wrong FS: hdfs://spark-master:8020/C835.HCC1143_BL.4.bam, expected: file:///
    at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:643)
    at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:79)
    at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:506)
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:724)
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:501)
    at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:397)
    at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1411)
    at $iwC$$iwC$$iwC$$iwC.<init>(<console>:17)
    at $iwC$$iwC$$iwC.<init>(<console>:22)
    at $iwC$$iwC.<init>(<console>:24)
    at $iwC.<init>(<console>:26)
    at <init>(<console>:28)
    at .<init>(<console>:32)
    at .<clinit>(<console>)
    at .<init>(<console>:7)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:852)
    at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1125)
    at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:674)
    at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:705)
    at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:669)
    at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:828)
    at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:873)
    at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:785)
    at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:628)
    at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:636)
    at org.apache.spark.repl.SparkILoop.loop(SparkILoop.scala:641)
    at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply$mcZ$sp(SparkILoop.scala:968)
    at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply(SparkILoop.scala:916)
    at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply(SparkILoop.scala:916)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:916)
    at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1011)
    at org.apache.spark.repl.Main$.main(Main.scala:31)
    at org.apache.spark.repl.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

scala> FileSystem.getDefaultUri(sc.hadoopConfiguration)
res4: java.net.URI = file:///

__
Setting HADOOP_HOME doesn’t fix

HADOOP_HOME=/opt/sparkbox/hadoop /usr/bin/time /home/sparkbox/adam-distribution_2.10-0.17.0/bin/adam-submit transform /C835.HCC1143_BL.4.bam hdfs://spark-master:8020/C835.HCC1143_BL.4.adam
Spark assembly has been built with Hive, including Datanucleus jars on classpath
2015-06-03 22:58:08 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NullPointerException

The problem wasn't just how the hdfs path was being interpreted

ADAM_OPTS=/usr/bin/time /home/sparkbox/adam-distribution_2.10-0.17.0/bin/adam-submit transform /C835.HCC1143_BL.4.bam hdfs://spark-master:8020/C835.HCC1143_BL.4.adam

Spark assembly has been built with Hive, including Datanucleus jars on classpath
java.lang.ClassNotFoundException: org.bdgenomics.adam.cli.ADAMMain
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:342)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---

**Comment by hannes-ucsc** [comment]
Resolved by a721bcf16fcf81452d62745cbc9452185acc8237.
