### ISSUE TITLE
cgcloud create dies on version.py

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#66]
- note: backtick formatting breaks down halfway this message, not sure why

Running from command line, not through virtualenv:
`cgcloud create -N -t t2.micro generic-ubuntu-trusty-box`

dies with

`[52.88.75.22] out:       File "/tmp/pip-DDY6u4-build/setup.py", line 5, in <module>
[52.88.75.22] out:         from version import cgcloud_version
[52.88.75.22] out:     ImportError: No module named version`

(for more context see below)

After ssh to the instance, 
`tar -ztvf cgcloud-lib-1.1a1.tar.gz`

(...)

`-rw-rw-r-- ubuntu/ubuntu   569 2015-09-28 16:16 cgcloud-lib-1.1a1/setup.py
lrwxrwxrwx ubuntu/ubuntu     0 2015-09-25 03:08 cgcloud-lib-1.1a1/MANIFEST.in -> ../MANIFEST.in
lrwxrwxrwx ubuntu/ubuntu     0 2015-09-25 03:08 cgcloud-lib-1.1a1/version.py -> ../version.py`

So version.py is linked to a nonexisting file one directory up (in /home/ubuntu)

`pip list`

`apt-xapian-index (0.45)
argcomplete (0.6.9)
argparse (1.2.1)
bd2k-python-lib (1.6.dev1)
boto (2.38.0)
cgcloud-core (1.1a1)
cgcloud-jenkins (1.1a1)
cgcloud-lib (1.1a1)
cgcloud-mesos (1.1a1)
cgcloud-spark (1.1a1)
cgcloud-toil (1.1a1)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
ecdsa (0.13)
Fabric (1.10.2)
html5lib (0.999)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
lxml (3.3.3)
oauth (1.0.1)
PAM (0.4.2)
paramiko (1.15.2)
pip (1.5.4)
prettytable (0.7.2)
pycrypto (2.6.1)
pycurl (7.19.3)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
ssh-import-id (3.21)
synapseclient (1.3)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)`

More context for error listed above:

```[52.88.75.22] out: Installed /opt/cgcloudagent/lib/python2.7/site-packages/pip-1.5.2-py2.7.egg
[52.88.75.22] out: Processing dependencies for pip==1.5.2
[52.88.75.22] out: Finished processing dependencies for pip==1.5.2
[52.88.75.22] out:

[52.88.75.22] run: /opt/cgcloudagent/bin/pip install --allow-external argparse /home/ubuntu/cgcloud-lib-1.1a1.tar.gz /home/ubuntu/cgcloud-agent-1.1a1.tar.gz
[52.88.75.22] out: Unpacking ./cgcloud-lib-1.1a1.tar.gz
[52.88.75.22] out:   Running setup.py (path:/tmp/pip-DDY6u4-build/setup.py) egg_info for package from file:///home/ubuntu/cgcloud-lib-1.1a1.tar.gz
[52.88.75.22] out:     Traceback (most recent call last):
[52.88.75.22] out:       File "<string>", line 17, in <module>
[52.88.75.22] out:       File "/tmp/pip-DDY6u4-build/setup.py", line 5, in <module>
[52.88.75.22] out:         from version import cgcloud_version
[52.88.75.22] out:     ImportError: No module named version
[52.88.75.22] out:     Complete output from command python setup.py egg_info:
[52.88.75.22] out:     Traceback (most recent call last):
[52.88.75.22] out:
[52.88.75.22] out:   File "<string>", line 17, in <module>
[52.88.75.22] out:
[52.88.75.22] out:   File "/tmp/pip-DDY6u4-build/setup.py", line 5, in <module>
[52.88.75.22] out:
[52.88.75.22] out:     from version import cgcloud_version
[52.88.75.22] out:
[52.88.75.22] out: ImportError: No module named version
[52.88.75.22] out:
[52.88.75.22] out: ----------------------------------------
[52.88.75.22] out: Cleaning up...
[52.88.75.22] out: Command python setup.py egg_info failed with error code 1 in /tmp/pip-DDY6u4-build
[52.88.75.22] out: Storing debug log for failure in /home/ubuntu/.pip/pip.log
[52.88.75.22] out:

Fatal error: run() received nonzero return code 1 while executing!

Requested: /opt/cgcloudagent/bin/pip install --allow-external argparse /home/ubuntu/cgcloud-lib-1.1a1.tar.gz /home/ubuntu/cgcloud-agent-1.1a1.tar.gz
Executed: /bin/bash -l -c "/opt/cgcloudagent/bin/pip install --allow-external argparse /home/ubuntu/cgcloud-lib-1.1a1.tar.gz /home/ubuntu/cgcloud-agent-1.1a1.tar.gz"

Aborting.```

**Comment by hannes-ucsc** [comment]
Great ticket. This should give me everything I need to fix it quickly.

**Comment by hannes-ucsc** [comment]
Use three back ticks in a separate line to start/end a block with pasted code. Single back ticks only work within a paragraph.

**Comment by hannes-ucsc** [comment]
This is being tested in CI as we speak. @Jeltje, you may want to test independently on your end.

**Comment by hannes-ucsc** [comment]
CI confirmed this as fixed. @adderan in this mornings scrum, you reported having this issue, too. This commit should fix it.

**Comment by Jeltje** [comment]
I can confirm that the fix works! I can now run `cgcloud create` without any further issues.
