### ISSUE TITLE
Mention pycrypto installation problem in README

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgcloud#7]
_From @hannes-ucsc on April 22, 2015 5:42_

User ran `sudo pip install git+https://github.com/BD2KGenomics/cgcloud-core.git`

Failed with 

```
    src/MD2.c:31:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
```

User installed python-dev: `sudo apt-get -y install python-dev`

User reran above `pip install` command:

```
ubuntu@ip-172-31-21-203:~$ sudo pip install --process-dependency-links git+https://github.com/BD2KGenomics/cgcloud-core.git
Downloading/unpacking git+https://github.com/BD2KGenomics/cgcloud-core.git
  Cloning https://github.com/BD2KGenomics/cgcloud-core.git to /tmp/pip-FOVrUr-build
  Running setup.py (path:/tmp/pip-FOVrUr-build/setup.py) egg_info for package from git+https://github.com/BD2KGenomics/cgcloud-core.git
    no previously-included directories found matching 'doc/.build'

    Installed /tmp/pip-FOVrUr-build/.eggs/nose-1.3.6-py2.7.egg

  Requirement already satisfied (use --upgrade to upgrade): cgcloud-core==1.0.dev1 from git+https://github.com/BD2KGenomics/cgcloud-core.git in /usr/local/lib/python2.7/dist-packages
  Dependency Links processing has been deprecated with an accelerated time schedule and will be removed in pip 1.6
Requirement already satisfied (use --upgrade to upgrade): bd2k-python-lib==1.5 in /usr/local/lib/python2.7/dist-packages (from cgcloud-core==1.0.dev1)
Requirement already satisfied (use --upgrade to upgrade): cgcloud-lib==1.0.dev1 in /usr/local/lib/python2.7/dist-packages (from cgcloud-core==1.0.dev1)
Requirement already satisfied (use --upgrade to upgrade): pkginfo>=1.1 in /usr/local/lib/python2.7/dist-packages (from cgcloud-core==1.0.dev1)
Requirement already satisfied (use --upgrade to upgrade): boto>=2.36.0 in /usr/local/lib/python2.7/dist-packages (from cgcloud-core==1.0.dev1)
Requirement already satisfied (use --upgrade to upgrade): Fabric>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from cgcloud-core==1.0.dev1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from cgcloud-core==1.0.dev1)
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.10 in /usr/local/lib/python2.7/dist-packages (from Fabric>=1.7.0->cgcloud-core==1.0.dev1)
Cleaning up...
```

So the installation of pycrypto was skipped even though it never completed successfully. User then ran cgcloud and hit this:

```
ubuntu@ip-172-31-21-203:~$ cgcloud register-key ~/.ssh/id_rsa.pub
Traceback (most recent call last):
  File "/usr/local/bin/cgcloud", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3057, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 639, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 940, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 827, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycrypto!=2.4,>=2.1' distribution was not found and is required by paramiko
```

User installed pycrypto explicitly: `sudo pip install pycrypto`. This went through because now `python-dev` was installed. That fixed the problem.

_Copied from original issue: BD2KGenomics/cgcloud-spark#6_

**Comment by hannes-ucsc** [comment]
Needs to be verified again now that cgcloud can be installed from PyPI.
