### ISSUE TITLE
create-cluster exits with error

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/cgcloud#82]
This is version 1.2.2

`cgcloud create-cluster --leader-instance-type m3.medium -t=c3.8xlarge -s 20 --share key_config/ toil`

The cluster gets created and works, but the setup exits with this 'I'm probably not important' error:

```
Exception in thread Thread-84 (most likely raised during interpreter shutdown):Exception in thread Thread-100 (most likely raised during interpreter shutdown):Exception in thread Thread-92 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
 Exception in thread Thread-76 (most likely raised during interpreter shutdown):Exception in thread Thread-104 (most likely raised during interpreter shutdown):  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner

Exception in thread Thread-68 (most likely raised during interpreter shutdown):

Traceback (most recent call last):Traceback (most recent call last):Exception in thread Thread-34 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Traceback (most recent call last):Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner


  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'Traceback (most recent call last):
  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'


  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-96 (most likely raised during interpreter shutdown):Exception in thread Thread-88 (most likely raised during interpreter shutdown):
Traceback (most recent call last):


Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
   File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run  File "/data/git/toil-scripts/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by hannes-ucsc** [comment]
The interesting bits in the log probably precede the snippet you posted here. Do you still have the console output in its entirety, and if so could you post it here?

**Comment by Jeltje** [comment]
Rats, I thought that was the whole thing.
Tried to reproduce it with a single worker box (instead of 20) but didn't get the error.

I guess close this issue until I can reproduce it?

**Comment by hannes-ucsc** [comment]
Please reopen if this happens again.
