### ISSUE TITLE
Running create-cluster with --spot-bid fails if it was never invoked without it

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/cgcloud#91]
```
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Value (<arn:aws>:iam::412039062076:instance-profile/heuermh_toil-leader) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN</Message>
```

**Comment by heuermh** [comment]
The next time I ran `cgcloud create-cluster` with `--spot-bid` it worked.

**Comment by hannes-ucsc** [comment]
```
$ cgcloud create-cluster -t m3.large --ebs-volume-size 30 --spot-bid 0.021 -s 2 toil
INFO: Using zone 'us-west-2a' and namespace '/heuermh/'
INFO: === Launching leader ===
INFO: Requesting spot instances in zone us-west-2b
Traceback (most recent call last):
  File "/home/ubuntu/cgcloud/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/lib/util.py", line 300, in run
    command.run( options )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/cluster_commands.py", line 115, in run
    super( CreateClusterCommand, self ).run( options )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 81, in run
    return self.run_in_ctx( options, ctx )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/cluster_commands.py", line 37, in run_in_ctx
    self.run_on_cluster_type( ctx, options, cluster_type )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/cluster_commands.py", line 121, in run_on_cluster_type
    self.run_on_role( options, ctx, self.cluster.leader_role )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 124, in run_on_role
    return self.run_on_box( options, box )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 471, in run_on_box
    box.terminate( wait=False )
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/commands.py", line 466, in run_on_box
    box.create( spec, wait_ready=True )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/box.py", line 556, in create
    reservations = self._create_spot_instances( spec )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/cgcloud/core/box.py", line 602, in _create_spot_instances
    requests = self.ctx.ec2.request_spot_instances( price, self.image_id, **spec )
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 1638, in request_spot_instances
    verb='POST')
  File "/home/ubuntu/cgcloud/local/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Value (arn:aws:iam::412039062076:instance-profile/heuermh_toil-leader) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN</Message></Error></Errors><RequestID>314f841a-6a41-4aae-8815-48e9f10419b4</RequestID></Response>

(cgcloud) ubuntu@ubuntu:~/cgcloud$ cgcloud create-cluster -t m3.large --ebs-volume-size 30 -s 2 toil
INFO: Using zone 'us-west-2a' and namespace '/heuermh/'
INFO: === Launching leader ===
INFO: Creating m3.large instance(s) ... 
INFO: ... created i-3162acf6.
INFO: Tagging instance ... 
INFO: ... instance tagged {'cluster_name': u'i-3162acf6', 'ebs_volume_size': '30', 'leader_instance_id': u'i-3162acf6', 'Name': u'heuermh_toil-leader', 'enable_agent': 'True', 'generation': '1', 'cluster_ordinal': '0'}.
INFO: ... waiting for instance i-3162acf6 ... 
INFO: ... running, waiting for assignment of public IP ... 
INFO: ... assigned, waiting for SSH port ... 
INFO: ... open ... 
INFO: ... testing SSH ... 
INFO: ... SSH working ..., 
INFO: ... instance ready.
```

**Comment by hannes-ucsc** [comment]
Turns out this is just an eventual consistency between instance profile creation and spot instance request. We already handle that for on-demand instances so we just need to also do that for spot instances.

**Comment by hannes-ucsc** [comment]
This is in 1.3.1 and on master.
